language: ruby
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
rvm:
  - jruby-1.7.25
before_install: gem install bundler -v 1.10.6
before_script:
 - bundle exec rake build:extension
script: 
 - bundle exec rake spec
